image: Visual Studio 2017

before_build:
  - msbuild /t:restore ./src/ReactiveDomain.sln
build:
  project: ./src/ReactiveDomain.sln  
test_script:
  - '%xunit20%\xunit.console.exe ./bld/Debug/net472/ReactiveDomain.Messaging.Tests.dll -appveyor'
  - '%xunit20%\xunit.console.exe ./bld/Debug/net472/ReactiveDomain.Buffers.Tests.dll -appveyor'
  - '%xunit20%\xunit.console.exe ./bld/Debug/net472/ReactiveDomain.Foundation.Tests.dll -appveyor'  
  - '%xunit20%\xunit.console.exe ./bld/Debug/net472/ReactiveDomain.PrivateLedger.Tests.dll -appveyor'
  - '%xunit20%\xunit.console.exe ./bld/Debug/net472/ReactiveDomain.Transport.Tests.dll -appveyor' 
  - '%xunit20%\xunit.console.exe ./bld/Debug/net472/ReactiveDomain.UI.Tests.dll -appveyor' 